import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import rateLimit from 'express-rate-limit';
import { z } from 'zod';
import { pool, transaction } from './db.js';
import { HttpError, asyncRoute, authenticate, validate, requireMessRole, requireCycleRole, requireSuperAdmin, membershipForCycle } from './http.js';

if (!process.env.JWT_ACCESS_SECRET || !process.env.JWT_REFRESH_SECRET) {
  throw new Error('JWT_ACCESS_SECRET and JWT_REFRESH_SECRET must be configured');
}

const app = express();
const port = Number(process.env.PORT || 4000);
const origins = (process.env.WEB_ORIGIN || 'http://localhost:5173').split(',').map((x) => x.trim());
app.set('trust proxy', 1);
app.use(helmet({ crossOriginResourcePolicy: false }));
app.use(cors({ origin(origin, callback) { callback(null, !origin || origins.includes(origin)); }, credentials: true }));
app.use(express.json({ limit: '2mb' }));
app.use(morgan(process.env.NODE_ENV === 'production' ? 'combined' : 'dev'));

const authLimit = rateLimit({ windowMs: 15 * 60 * 1000, limit: 50, standardHeaders: true, legacyHeaders: false });
const accessToken = (user) => jwt.sign({ id: user.id, email: user.email, systemRole:user.systemRole || 'user', mustChangePassword: Boolean(user.mustChangePassword) }, process.env.JWT_ACCESS_SECRET, { expiresIn: '15m' });
const refreshToken = (user) => jwt.sign({ id: user.id, type: 'refresh' }, process.env.JWT_REFRESH_SECRET, { expiresIn: '30d' });
const publicUser = (u) => ({ id: u.id, name: u.name, email: u.email, phone: u.phone, avatarUrl: u.avatarUrl, systemRole:u.systemRole || 'user', mustChangePassword: Boolean(u.mustChangePassword), avatar: u.name.split(/\s+/).map((x) => x[0]).join('').slice(0, 2).toUpperCase() });
const logActivity = (conn, messId, userId, action, entityType, entityId, meta = null) => conn.execute('INSERT INTO activity_logs(mess_id,user_id,action,entity_type,entity_id,meta) VALUES(?,?,?,?,?,?)', [messId, userId, action, entityType, entityId, meta ? JSON.stringify(meta) : null]);
const avatarColors = ['#6d5dfc','#f97357','#16a085','#e9a23b','#3c82f6','#c05adb'];

async function cycleRow(cycleId, conn = pool) {
  const [rows] = await conn.execute(`SELECT id,mess_id AS messId,cycle_year AS year,cycle_month AS month,status,total_bazar_amount AS totalBazarAmount,total_other_cost AS totalOtherCost,total_meals AS totalMeals,meal_rate AS mealRate,closed_at AS closedAt FROM mess_cycles WHERE id=?`, [cycleId]);
  if (!rows[0]) throw new HttpError(404, 'Cycle not found');
  return rows[0];
}

async function liveSummary(conn, id) {
  const cycle = await cycleRow(id, conn);
  if (cycle.status === 'closed') {
    const [stored] = await conn.execute(`SELECT mms.mess_member_id AS id,u.name,u.email,mm.role,mms.total_meals AS meals,mms.meal_cost AS mealCost,mms.other_cost_share AS otherShare,mms.total_cost AS totalCost,mms.total_deposit AS deposit,mms.opening_due AS openingDue,mms.balance,mms.status FROM member_month_summary mms JOIN mess_members mm ON mm.id=mms.mess_member_id JOIN users u ON u.id=mm.user_id WHERE mms.cycle_id=? ORDER BY u.name`, [id]);
    return { cycle, totals: { bazar: cycle.totalBazarAmount, otherCost: cycle.totalOtherCost, meals: cycle.totalMeals, deposits: stored.reduce((s,x)=>s+x.deposit,0) }, members: stored.map((x,i)=>({ ...x, avatar:x.name.split(/\s+/).map(n=>n[0]).join('').slice(0,2), color:avatarColors[i%avatarColors.length] })) };
  }
  const [members] = await conn.execute(`SELECT mm.id,u.name,u.email,mm.role,cms.opening_due AS openingDue,COALESCE(mt.meals,0) AS meals,COALESCE(dt.deposit,0) AS deposit FROM cycle_member_status cms JOIN mess_members mm ON mm.id=cms.mess_member_id JOIN users u ON u.id=mm.user_id LEFT JOIN (SELECT mess_member_id,SUM(breakfast+lunch+dinner+guest_meals) meals FROM meals WHERE cycle_id=? GROUP BY mess_member_id) mt ON mt.mess_member_id=mm.id LEFT JOIN (SELECT mess_member_id,SUM(amount) deposit FROM deposits WHERE cycle_id=? GROUP BY mess_member_id) dt ON dt.mess_member_id=mm.id WHERE cms.cycle_id=? AND cms.is_active=1 ORDER BY u.name`, [id,id,id]);
  const [[bazar]] = await conn.execute('SELECT COALESCE(SUM(total_amount),0) total FROM bazar_entries WHERE cycle_id=?', [id]);
  const [[costs]] = await conn.execute(`SELECT COALESCE(SUM(amount),0) total,COALESCE(SUM(CASE WHEN split_type='equal' THEN amount ELSE 0 END),0) equalTotal,COALESCE(SUM(CASE WHEN split_type='meal_based' THEN amount ELSE 0 END),0) mealTotal FROM other_costs WHERE cycle_id=?`, [id]);
  const totalMeals = members.reduce((s,x)=>s+x.meals,0), mealRate = totalMeals ? bazar.total/totalMeals : 0;
  const round = (n) => Math.round((n + Number.EPSILON) * 100) / 100;
  const calculated = members.map((x,i) => { const mealCost=x.meals*mealRate; const otherShare=(members.length?costs.equalTotal/members.length:0)+(totalMeals?costs.mealTotal*x.meals/totalMeals:0); const totalCost=mealCost+otherShare; const balance=x.deposit+x.openingDue-totalCost; return {...x,mealCost:round(mealCost),otherShare:round(otherShare),totalCost:round(totalCost),balance:round(balance),status:balance>.005?'refund':balance<-.005?'due':'settled',avatar:x.name.split(/\s+/).map(n=>n[0]).join('').slice(0,2),color:avatarColors[i%avatarColors.length]}; });
  return { cycle: { ...cycle, mealRate: round(mealRate) }, totals: { bazar: round(bazar.total), otherCost: round(costs.total), meals: round(totalMeals), deposits: round(members.reduce((s,x)=>s+x.deposit,0)) }, members: calculated };
}

app.get('/api/health', asyncRoute(async (req,res) => { await pool.query('SELECT 1'); res.json({ok:true,database:'connected'}); }));

const registerSchema = z.object({ name:z.string().trim().min(2).max(100), email:z.string().email().max(150), phone:z.string().max(20).optional(), password:z.string().min(8).max(72) });
app.post('/api/auth/register', authLimit, validate(registerSchema), asyncRoute(async (req,res) => {
  const {name,email,phone,password}=req.validated; const [exists]=await pool.execute('SELECT id FROM users WHERE email=? LIMIT 1',[email.toLowerCase()]); if(exists.length) throw new HttpError(409,'An account already exists for this email');
  const hash=await bcrypt.hash(password,12); const [result]=await pool.execute('INSERT INTO users(name,email,phone,password_hash) VALUES(?,?,?,?)',[name,email.toLowerCase(),phone||null,hash]); const user={id:result.insertId,name,email:email.toLowerCase(),phone}; res.status(201).json({accessToken:accessToken(user),refreshToken:refreshToken(user),token:accessToken(user),user:publicUser(user)});
}));
app.post('/api/auth/login', authLimit, validate(z.object({email:z.string().email(),password:z.string().min(1)})), asyncRoute(async (req,res) => {
  const [rows]=await pool.execute('SELECT id,name,email,phone,password_hash AS passwordHash,must_change_password AS mustChangePassword,system_role AS systemRole,avatar_url AS avatarUrl FROM users WHERE email=? AND is_active=1 LIMIT 1',[req.validated.email.toLowerCase()]); const user=rows[0]; if(!user || !await bcrypt.compare(req.validated.password,user.passwordHash)) throw new HttpError(401,'Email or password is incorrect');
  const access=accessToken(user); res.json({accessToken:access,refreshToken:refreshToken(user),token:access,user:publicUser(user)});
}));
app.post('/api/auth/refresh', validate(z.object({refreshToken:z.string().min(20)})), asyncRoute(async(req,res)=>{ let decoded; try{decoded=jwt.verify(req.validated.refreshToken,process.env.JWT_REFRESH_SECRET);}catch{throw new HttpError(401,'Refresh token is invalid or expired');} if(decoded.type!=='refresh') throw new HttpError(401,'Invalid refresh token'); const [rows]=await pool.execute('SELECT id,name,email,must_change_password AS mustChangePassword,system_role AS systemRole FROM users WHERE id=? AND is_active=1',[decoded.id]); if(!rows[0]) throw new HttpError(401,'Account is unavailable'); res.json({accessToken:accessToken(rows[0])}); }));
app.get('/api/auth/me', authenticate, asyncRoute(async(req,res)=>{const [rows]=await pool.execute('SELECT id,name,email,phone,must_change_password AS mustChangePassword,system_role AS systemRole,avatar_url AS avatarUrl FROM users WHERE id=?',[req.user.id]);if(!rows[0])throw new HttpError(404,'User not found');res.json(publicUser(rows[0]));}));
app.post('/api/auth/change-password', authenticate, validate(z.object({currentPassword:z.string().min(1),newPassword:z.string().min(8).max(72)})), asyncRoute(async(req,res)=>{
  const [[user]]=await pool.execute('SELECT id,name,email,phone,password_hash AS passwordHash,must_change_password AS mustChangePassword,system_role AS systemRole FROM users WHERE id=? AND is_active=1',[req.user.id]);
  if(!user || !await bcrypt.compare(req.validated.currentPassword,user.passwordHash)) throw new HttpError(400,'Current password is incorrect');
  if(req.validated.currentPassword===req.validated.newPassword) throw new HttpError(400,'Choose a password different from the temporary password');
  const hash=await bcrypt.hash(req.validated.newPassword,12); await pool.execute('UPDATE users SET password_hash=?,must_change_password=0 WHERE id=?',[hash,user.id]);
  user.mustChangePassword=false; const token=accessToken(user); res.json({token,accessToken:token,user:publicUser(user)});
}));

app.use('/api', authenticate);
app.use('/api', (req,res,next)=>{if(req.user.mustChangePassword)return next(new HttpError(403,'You must change your temporary password before continuing'));next();});

app.post('/api/messes', requireSuperAdmin, validate(z.object({name:z.string().min(2).max(150),address:z.string().max(255).optional(),currency:z.string().min(3).max(10).default('BDT')})), asyncRoute(async(req,res)=>{const mess=await transaction(async(conn)=>{const [r]=await conn.execute('INSERT INTO messes(name,address,currency,created_by) VALUES(?,?,?,?)',[req.validated.name,req.validated.address||null,req.validated.currency,req.user.id]);await conn.execute("INSERT INTO mess_members(mess_id,user_id,role,joined_at,status) VALUES(?,?,'manager',CURDATE(),'active')",[r.insertId,req.user.id]);return{id:r.insertId,...req.validated};});res.status(201).json(mess);}));
app.get('/api/messes', asyncRoute(async(req,res)=>{const[[account]]=await pool.execute('SELECT system_role AS systemRole FROM users WHERE id=?',[req.user.id]);if(account?.systemRole==='super_admin'){const[rows]=await pool.execute(`SELECT m.id,m.name,m.address,m.currency,COALESCE(mm.role,'super_admin') role FROM messes m LEFT JOIN mess_members mm ON mm.mess_id=m.id AND mm.user_id=? WHERE m.is_active=1 ORDER BY m.name`,[req.user.id]);return res.json(rows);}const [rows]=await pool.execute(`SELECT m.id,m.name,m.address,m.currency,mm.role FROM mess_members mm JOIN messes m ON m.id=mm.mess_id WHERE mm.user_id=? AND mm.status='active' AND m.is_active=1 ORDER BY m.name`,[req.user.id]);res.json(rows);}));
app.get('/api/messes/:id', requireMessRole(), asyncRoute(async(req,res)=>{const [rows]=await pool.execute('SELECT id,name,address,currency,is_active AS isActive FROM messes WHERE id=?',[req.params.id]);res.json(rows[0]);}));
app.put('/api/messes/:id', requireMessRole('manager'), validate(z.object({name:z.string().min(2).max(150),address:z.string().max(255).nullable().optional(),currency:z.string().min(3).max(10)})), asyncRoute(async(req,res)=>{await pool.execute('UPDATE messes SET name=?,address=?,currency=? WHERE id=?',[req.validated.name,req.validated.address||null,req.validated.currency,req.params.id]);res.json({id:+req.params.id,...req.validated});}));

app.get('/api/messes/:id/members', requireMessRole(), asyncRoute(async(req,res)=>{const [rows]=await pool.execute(`SELECT mm.id,mm.mess_id AS messId,u.name,u.email,u.phone,mm.role,mm.status,DATE_FORMAT(mm.joined_at,'%Y-%m-%d') joinedAt FROM mess_members mm JOIN users u ON u.id=mm.user_id WHERE mm.mess_id=? ORDER BY mm.status,u.name`,[req.params.id]);res.json(rows);}));
app.post('/api/messes/:id/members', requireMessRole('manager'), validate(z.object({name:z.string().min(2),email:z.string().email(),role:z.enum(['manager','member']).default('member')})), asyncRoute(async(req,res)=>{const result=await transaction(async(conn)=>{let [[user]]=await conn.execute('SELECT id,name,email FROM users WHERE email=?',[req.validated.email.toLowerCase()]);let temporaryPassword=null;if(!user){temporaryPassword='D123';const temporary=await bcrypt.hash(temporaryPassword,12);const [u]=await conn.execute('INSERT INTO users(name,email,password_hash,must_change_password) VALUES(?,?,?,1)',[req.validated.name,req.validated.email.toLowerCase(),temporary]);user={id:u.insertId,name:req.validated.name,email:req.validated.email.toLowerCase()};}const [m]=await conn.execute("INSERT INTO mess_members(mess_id,user_id,role,joined_at,status) VALUES(?,?,?,CURDATE(),'active') ON DUPLICATE KEY UPDATE role=VALUES(role),status='active',left_at=NULL",[req.params.id,user.id,req.validated.role]);const [[member]]=await conn.execute('SELECT id FROM mess_members WHERE mess_id=? AND user_id=?',[req.params.id,user.id]);const [[cycle]]=await conn.execute("SELECT id FROM mess_cycles WHERE mess_id=? AND status='open' ORDER BY cycle_year DESC,cycle_month DESC LIMIT 1",[req.params.id]);if(cycle)await conn.execute('INSERT IGNORE INTO cycle_member_status(cycle_id,mess_member_id,is_active,opening_due) VALUES(?,?,1,0)',[cycle.id,member.id]);await logActivity(conn,+req.params.id,req.user.id,'member.add','mess_member',member.id);return{id:member.id,...user,role:req.validated.role,active:true,temporaryPassword};});res.status(201).json(result);}));
app.put('/api/messes/:id/members/:memberId', requireMessRole('manager'), validate(z.object({role:z.enum(['manager','member']),status:z.enum(['active','inactive'])})), asyncRoute(async(req,res)=>{await pool.execute('UPDATE mess_members SET role=?,status=?,left_at=IF(?=\'inactive\',CURDATE(),NULL) WHERE id=? AND mess_id=?',[req.validated.role,req.validated.status,req.validated.status,req.params.memberId,req.params.id]);res.json({ok:true});}));

app.get('/api/messes/:id/cycles', requireMessRole(), asyncRoute(async(req,res)=>{const [rows]=await pool.execute('SELECT id,cycle_year AS year,cycle_month AS month,status,total_bazar_amount AS totalBazarAmount,total_other_cost AS totalOtherCost,total_meals AS totalMeals,meal_rate AS mealRate FROM mess_cycles WHERE mess_id=? ORDER BY cycle_year DESC,cycle_month DESC',[req.params.id]);res.json(rows);}));
app.post('/api/messes/:id/cycles', requireSuperAdmin, validate(z.object({year:z.number().int().min(2020).max(2100),month:z.number().int().min(1).max(12)})), asyncRoute(async(req,res)=>{const cycle=await transaction(async(conn)=>{const[[mess]]=await conn.execute('SELECT id FROM messes WHERE id=? AND is_active=1',[req.params.id]);if(!mess)throw new HttpError(404,'Mess not found');const [r]=await conn.execute('INSERT INTO mess_cycles(mess_id,cycle_year,cycle_month) VALUES(?,?,?)',[req.params.id,req.validated.year,req.validated.month]);const [previous]=await conn.execute(`SELECT cms.mess_member_id,cms.is_active FROM cycle_member_status cms JOIN mess_cycles c ON c.id=cms.cycle_id WHERE c.mess_id=? AND c.id<>? ORDER BY c.cycle_year DESC,c.cycle_month DESC`,[req.params.id,r.insertId]);const defaults=new Map(previous.map(x=>[x.mess_member_id,x.is_active]));const [members]=await conn.execute("SELECT id FROM mess_members WHERE mess_id=? AND status='active'",[req.params.id]);for(const m of members)await conn.execute('INSERT INTO cycle_member_status(cycle_id,mess_member_id,is_active,opening_due) VALUES(?,?,?,0)',[r.insertId,m.id,defaults.get(m.id)??1]);return{id:r.insertId,messId:+req.params.id,...req.validated,status:'open'};});res.status(201).json(cycle);}));
app.get('/api/cycles/:id', requireCycleRole(), asyncRoute(async(req,res)=>res.json(await cycleRow(req.params.id))));
app.get('/api/cycles/:id/members', requireCycleRole(), asyncRoute(async(req,res)=>{const [rows]=await pool.execute(`SELECT mm.id,u.name,u.email,mm.role,cms.is_active AS active,cms.opening_due AS openingDue,cms.note FROM cycle_member_status cms JOIN mess_members mm ON mm.id=cms.mess_member_id JOIN users u ON u.id=mm.user_id WHERE cms.cycle_id=? ORDER BY u.name`,[req.params.id]);res.json(rows);}));
app.patch('/api/cycles/:id/members/:memberId', requireCycleRole('manager'), validate(z.object({active:z.boolean(),openingDue:z.number().optional()})), asyncRoute(async(req,res)=>{await pool.execute('UPDATE cycle_member_status SET is_active=?,opening_due=COALESCE(?,opening_due) WHERE cycle_id=? AND mess_member_id=?',[req.validated.active,req.validated.openingDue??null,req.params.id,req.params.memberId]);res.json({ok:true});}));

const ensureOpen=async(id)=>{const cycle=await cycleRow(id);if(cycle.status!=='open')throw new HttpError(409,'This cycle is closed and cannot be changed');return cycle;};
app.get('/api/cycles/:id/meals', requireCycleRole(), asyncRoute(async(req,res)=>{const [rows]=await pool.execute(`SELECT id,mess_member_id AS memberId,DATE_FORMAT(meal_date,'%Y-%m-%d') date,breakfast,lunch,dinner,guest_meals AS guest FROM meals WHERE cycle_id=? ORDER BY meal_date DESC`,[req.params.id]);res.json(rows);}));
app.post('/api/cycles/:id/meals', requireCycleRole(), validate(z.object({memberId:z.number().int(),date:z.string(),breakfast:z.number().min(0),lunch:z.number().min(0),dinner:z.number().min(0),guest:z.number().min(0).default(0)})), asyncRoute(async(req,res)=>{await ensureOpen(req.params.id);if(req.membership.role!=='manager'&&req.membership.id!==req.validated.memberId)throw new HttpError(403,'Members may only record their own meals');const b=req.validated;await pool.execute(`INSERT INTO meals(cycle_id,mess_member_id,meal_date,breakfast,lunch,dinner,guest_meals) VALUES(?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE breakfast=VALUES(breakfast),lunch=VALUES(lunch),dinner=VALUES(dinner),guest_meals=VALUES(guest_meals)`,[req.params.id,b.memberId,b.date,b.breakfast,b.lunch,b.dinner,b.guest]);res.status(201).json({ok:true});}));
app.get('/api/cycles/:id/bazar', requireCycleRole(), asyncRoute(async(req,res)=>{const [rows]=await pool.execute(`SELECT be.id,be.mess_member_id AS memberId,DATE_FORMAT(be.bazar_date,'%Y-%m-%d') date,be.note,be.total_amount AS total,JSON_ARRAYAGG(JSON_OBJECT('product',bi.product_name,'quantity',bi.quantity,'unit',bi.unit,'unitPrice',bi.unit_price,'subtotal',bi.sub_total)) items FROM bazar_entries be LEFT JOIN bazar_items bi ON bi.bazar_entry_id=be.id WHERE be.cycle_id=? GROUP BY be.id ORDER BY be.bazar_date DESC`,[req.params.id]);res.json(rows);}));
app.post('/api/cycles/:id/bazar', requireCycleRole('manager'), validate(z.object({memberId:z.number().int(),date:z.string(),note:z.string().max(255).default(''),items:z.array(z.object({product:z.string().min(1),quantity:z.number().positive(),unit:z.string().max(20),unitPrice:z.number().min(0)})).min(1)})), asyncRoute(async(req,res)=>{const cycle=await ensureOpen(req.params.id);const entry=await transaction(async(conn)=>{const items=req.validated.items.map(x=>({...x,subtotal:Math.round(x.quantity*x.unitPrice*100)/100}));const total=items.reduce((s,x)=>s+x.subtotal,0);const [r]=await conn.execute('INSERT INTO bazar_entries(cycle_id,mess_member_id,bazar_date,total_amount,note) VALUES(?,?,?,?,?)',[req.params.id,req.validated.memberId,req.validated.date,total,req.validated.note]);for(const x of items)await conn.execute('INSERT INTO bazar_items(bazar_entry_id,product_name,quantity,unit,unit_price,sub_total) VALUES(?,?,?,?,?,?)',[r.insertId,x.product,x.quantity,x.unit,x.unitPrice,x.subtotal]);await logActivity(conn,cycle.messId,req.user.id,'bazar.create','bazar_entry',r.insertId);return{id:r.insertId,...req.validated,items,total};});res.status(201).json(entry);}));
app.get('/api/cycles/:id/deposits', requireCycleRole(), asyncRoute(async(req,res)=>{let sql=`SELECT id,mess_member_id AS memberId,amount,DATE_FORMAT(deposit_date,'%Y-%m-%d') date,payment_method AS method,note FROM deposits WHERE cycle_id=?`,params=[req.params.id];if(req.membership.role!=='manager'){sql+=' AND mess_member_id=?';params.push(req.membership.id);}sql+=' ORDER BY deposit_date DESC';const[rows]=await pool.execute(sql,params);res.json(rows);}));
app.post('/api/cycles/:id/deposits', requireCycleRole('manager'), validate(z.object({memberId:z.number().int(),amount:z.number().positive(),date:z.string(),method:z.enum(['cash','bkash','nagad','bank','other']),note:z.string().max(255).optional()})), asyncRoute(async(req,res)=>{const cycle=await ensureOpen(req.params.id),b=req.validated;const[r]=await pool.execute('INSERT INTO deposits(cycle_id,mess_member_id,amount,deposit_date,payment_method,note,received_by) VALUES(?,?,?,?,?,?,?)',[req.params.id,b.memberId,b.amount,b.date,b.method,b.note||null,req.user.id]);await logActivity(pool,cycle.messId,req.user.id,'deposit.create','deposit',r.insertId);res.status(201).json({id:r.insertId,...b});}));
app.get('/api/cycles/:id/other-costs', requireCycleRole(), asyncRoute(async(req,res)=>{const[rows]=await pool.execute(`SELECT id,category,title,amount,DATE_FORMAT(cost_date,'%Y-%m-%d') date,split_type AS splitType,note FROM other_costs WHERE cycle_id=? ORDER BY cost_date DESC`,[req.params.id]);res.json(rows);}));
const costSchema=z.object({title:z.string().min(2).max(150),category:z.enum(['utility','rent','servant','maintenance','other']),amount:z.number().positive(),date:z.string(),splitType:z.enum(['equal','meal_based']),note:z.string().max(255).optional()});
const addCost=asyncRoute(async(req,res)=>{await ensureOpen(req.params.id);const b=req.validated;const[r]=await pool.execute('INSERT INTO other_costs(cycle_id,category,title,amount,cost_date,split_type,note) VALUES(?,?,?,?,?,?,?)',[req.params.id,b.category,b.title,b.amount,b.date,b.splitType,b.note||null]);res.status(201).json({id:r.insertId,...b});});
app.post('/api/cycles/:id/other-costs',requireCycleRole('manager'),validate(costSchema),addCost);app.post('/api/cycles/:id/costs',requireCycleRole('manager'),validate(costSchema),addCost);
app.get('/api/cycles/:id/summary', requireCycleRole(), asyncRoute(async(req,res)=>{const summary=await liveSummary(pool,+req.params.id);if(req.membership.role!=='manager')summary.members=summary.members.filter(x=>x.id===req.membership.id);res.json(summary);}));
app.get('/api/cycles/:id/summary/:memberId', requireCycleRole(), asyncRoute(async(req,res)=>{if(req.membership.role!=='manager'&&req.membership.id!==+req.params.memberId)throw new HttpError(403,'You may only view your own statement');const summary=await liveSummary(pool,+req.params.id);const member=summary.members.find(x=>x.id===+req.params.memberId);if(!member)throw new HttpError(404,'Statement not found');res.json({cycle:summary.cycle,totals:summary.totals,member});}));
app.put('/api/cycles/:id/close', requireCycleRole('manager'), asyncRoute(async(req,res)=>{const result=await transaction(async(conn)=>{const summary=await liveSummary(conn,+req.params.id);if(summary.cycle.status!=='open')throw new HttpError(409,'Cycle is already closed');for(const m of summary.members)await conn.execute(`INSERT INTO member_month_summary(cycle_id,mess_member_id,total_meals,meal_cost,other_cost_share,total_cost,total_deposit,opening_due,balance,status) VALUES(?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE total_meals=VALUES(total_meals),meal_cost=VALUES(meal_cost),other_cost_share=VALUES(other_cost_share),total_cost=VALUES(total_cost),total_deposit=VALUES(total_deposit),opening_due=VALUES(opening_due),balance=VALUES(balance),status=VALUES(status)`,[req.params.id,m.id,m.meals,m.mealCost,m.otherShare,m.totalCost,m.deposit,m.openingDue,m.balance,m.status]);await conn.execute("UPDATE mess_cycles SET status='closed',total_bazar_amount=?,total_other_cost=?,total_meals=?,meal_rate=?,closed_at=NOW(),closed_by=? WHERE id=?",[summary.totals.bazar,summary.totals.otherCost,summary.totals.meals,summary.cycle.mealRate,req.user.id,req.params.id]);await logActivity(conn,summary.cycle.messId,req.user.id,'cycle.close','mess_cycle',+req.params.id,{members:summary.members.length});return summary;});res.json(result);}));

async function dashboardForCycle(cycleId,userId) {
  const cycle=await cycleRow(cycleId);
  const[[mess]]=await pool.execute(`SELECT m.id,m.name,m.address,m.currency,mm.role FROM mess_cycles mc JOIN messes m ON m.id=mc.mess_id JOIN mess_members mm ON mm.mess_id=m.id WHERE mc.id=? AND mm.user_id=? AND mm.status='active' LIMIT 1`,[cycleId,userId]);
  if(!mess)throw new HttpError(403,'You do not belong to this mess');
  const summary=await liveSummary(pool,+cycleId);
  const[members]=await pool.execute(`SELECT mm.id,u.name,u.email,mm.role,COALESCE(cms.is_active,0) AS active,mm.status AS membershipStatus FROM mess_members mm JOIN users u ON u.id=mm.user_id LEFT JOIN cycle_member_status cms ON cms.mess_member_id=mm.id AND cms.cycle_id=? WHERE mm.mess_id=? ORDER BY u.name`,[cycleId,mess.id]);
  members.forEach((m,i)=>{m.avatar=m.name.split(/\s+/).map(n=>n[0]).join('').slice(0,2);m.color=avatarColors[i%avatarColors.length];});
  const[meals]=await pool.execute(`SELECT id,mess_member_id AS memberId,DATE_FORMAT(meal_date,'%Y-%m-%d') date,breakfast,lunch,dinner,guest_meals AS guest FROM meals WHERE cycle_id=? ORDER BY meal_date DESC`,[cycleId]);
  const[bazar]=await pool.execute(`SELECT be.id,be.mess_member_id AS memberId,DATE_FORMAT(be.bazar_date,'%Y-%m-%d') date,be.note,be.total_amount AS total,JSON_ARRAYAGG(JSON_OBJECT('product',bi.product_name,'quantity',bi.quantity,'unit',bi.unit,'unitPrice',bi.unit_price)) items FROM bazar_entries be LEFT JOIN bazar_items bi ON bi.bazar_entry_id=be.id WHERE be.cycle_id=? GROUP BY be.id ORDER BY be.bazar_date DESC`,[cycleId]);
  const[deposits]=await pool.execute(`SELECT id,mess_member_id AS memberId,amount,DATE_FORMAT(deposit_date,'%Y-%m-%d') date,payment_method AS method FROM deposits WHERE cycle_id=? ORDER BY deposit_date DESC`,[cycleId]);
  const[costs]=await pool.execute(`SELECT id,category,title,amount,DATE_FORMAT(cost_date,'%Y-%m-%d') date,split_type AS splitType FROM other_costs WHERE cycle_id=? ORDER BY cost_date DESC`,[cycleId]);
  return{mess,cycle,summary,members,meals,bazar,deposits,costs};
}

app.get('/api/cycles/:id/dashboard',requireCycleRole(),asyncRoute(async(req,res)=>res.json(await dashboardForCycle(+req.params.id,req.user.id))));

// Manager CRUD routes. All writes verify that the record belongs to the URL cycle,
// reject closed months, and preserve an audit trail.
const mealWriteSchema=z.object({memberId:z.number().int(),date:z.string(),breakfast:z.number().min(0),lunch:z.number().min(0),dinner:z.number().min(0),guest:z.number().min(0).default(0)});
app.put('/api/cycles/:id/meals/:entryId',requireCycleRole('manager'),validate(mealWriteSchema),asyncRoute(async(req,res)=>{const cycle=await ensureOpen(req.params.id),b=req.validated;const[r]=await pool.execute('UPDATE meals SET mess_member_id=?,meal_date=?,breakfast=?,lunch=?,dinner=?,guest_meals=? WHERE id=? AND cycle_id=?',[b.memberId,b.date,b.breakfast,b.lunch,b.dinner,b.guest,req.params.entryId,req.params.id]);if(!r.affectedRows)throw new HttpError(404,'Meal entry not found');await logActivity(pool,cycle.messId,req.user.id,'meal.update','meal',+req.params.entryId);res.json({id:+req.params.entryId,...b});}));
app.delete('/api/cycles/:id/meals/:entryId',requireCycleRole('manager'),asyncRoute(async(req,res)=>{const cycle=await ensureOpen(req.params.id);const[r]=await pool.execute('DELETE FROM meals WHERE id=? AND cycle_id=?',[req.params.entryId,req.params.id]);if(!r.affectedRows)throw new HttpError(404,'Meal entry not found');await logActivity(pool,cycle.messId,req.user.id,'meal.delete','meal',+req.params.entryId);res.json({ok:true});}));

const bazarWriteSchema=z.object({memberId:z.number().int(),date:z.string(),note:z.string().max(255).default(''),items:z.array(z.object({product:z.string().min(1),quantity:z.number().positive(),unit:z.string().max(20),unitPrice:z.number().min(0)})).min(1)});
app.put('/api/cycles/:id/bazar/:entryId',requireCycleRole('manager'),validate(bazarWriteSchema),asyncRoute(async(req,res)=>{const cycle=await ensureOpen(req.params.id);const entry=await transaction(async(conn)=>{const[[exists]]=await conn.execute('SELECT id FROM bazar_entries WHERE id=? AND cycle_id=?',[req.params.entryId,req.params.id]);if(!exists)throw new HttpError(404,'Bazar entry not found');const items=req.validated.items.map(x=>({...x,subtotal:Math.round(x.quantity*x.unitPrice*100)/100})),total=items.reduce((s,x)=>s+x.subtotal,0);await conn.execute('UPDATE bazar_entries SET mess_member_id=?,bazar_date=?,note=?,total_amount=? WHERE id=?',[req.validated.memberId,req.validated.date,req.validated.note,total,req.params.entryId]);await conn.execute('DELETE FROM bazar_items WHERE bazar_entry_id=?',[req.params.entryId]);for(const x of items)await conn.execute('INSERT INTO bazar_items(bazar_entry_id,product_name,quantity,unit,unit_price,sub_total) VALUES(?,?,?,?,?,?)',[req.params.entryId,x.product,x.quantity,x.unit,x.unitPrice,x.subtotal]);await logActivity(conn,cycle.messId,req.user.id,'bazar.update','bazar_entry',+req.params.entryId);return{id:+req.params.entryId,...req.validated,items,total};});res.json(entry);}));
app.delete('/api/cycles/:id/bazar/:entryId',requireCycleRole('manager'),asyncRoute(async(req,res)=>{const cycle=await ensureOpen(req.params.id);const[r]=await pool.execute('DELETE FROM bazar_entries WHERE id=? AND cycle_id=?',[req.params.entryId,req.params.id]);if(!r.affectedRows)throw new HttpError(404,'Bazar entry not found');await logActivity(pool,cycle.messId,req.user.id,'bazar.delete','bazar_entry',+req.params.entryId);res.json({ok:true});}));

const depositWriteSchema=z.object({memberId:z.number().int(),amount:z.number().positive(),date:z.string(),method:z.enum(['cash','bkash','nagad','bank','other']),note:z.string().max(255).optional()});
app.put('/api/cycles/:id/deposits/:entryId',requireCycleRole('manager'),validate(depositWriteSchema),asyncRoute(async(req,res)=>{const cycle=await ensureOpen(req.params.id),b=req.validated;const[r]=await pool.execute('UPDATE deposits SET mess_member_id=?,amount=?,deposit_date=?,payment_method=?,note=? WHERE id=? AND cycle_id=?',[b.memberId,b.amount,b.date,b.method,b.note||null,req.params.entryId,req.params.id]);if(!r.affectedRows)throw new HttpError(404,'Deposit not found');await logActivity(pool,cycle.messId,req.user.id,'deposit.update','deposit',+req.params.entryId);res.json({id:+req.params.entryId,...b});}));
app.delete('/api/cycles/:id/deposits/:entryId',requireCycleRole('manager'),asyncRoute(async(req,res)=>{const cycle=await ensureOpen(req.params.id);const[r]=await pool.execute('DELETE FROM deposits WHERE id=? AND cycle_id=?',[req.params.entryId,req.params.id]);if(!r.affectedRows)throw new HttpError(404,'Deposit not found');await logActivity(pool,cycle.messId,req.user.id,'deposit.delete','deposit',+req.params.entryId);res.json({ok:true});}));

app.put('/api/cycles/:id/costs/:entryId',requireCycleRole('manager'),validate(costSchema),asyncRoute(async(req,res)=>{const cycle=await ensureOpen(req.params.id),b=req.validated;const[r]=await pool.execute('UPDATE other_costs SET category=?,title=?,amount=?,cost_date=?,split_type=?,note=? WHERE id=? AND cycle_id=?',[b.category,b.title,b.amount,b.date,b.splitType,b.note||null,req.params.entryId,req.params.id]);if(!r.affectedRows)throw new HttpError(404,'Cost not found');await logActivity(pool,cycle.messId,req.user.id,'cost.update','other_cost',+req.params.entryId);res.json({id:+req.params.entryId,...b});}));
app.delete('/api/cycles/:id/costs/:entryId',requireCycleRole('manager'),asyncRoute(async(req,res)=>{const cycle=await ensureOpen(req.params.id);const[r]=await pool.execute('DELETE FROM other_costs WHERE id=? AND cycle_id=?',[req.params.entryId,req.params.id]);if(!r.affectedRows)throw new HttpError(404,'Cost not found');await logActivity(pool,cycle.messId,req.user.id,'cost.delete','other_cost',+req.params.entryId);res.json({ok:true});}));

app.delete('/api/messes/:id/members/:memberId',requireMessRole('manager'),asyncRoute(async(req,res)=>{const[[target]]=await pool.execute('SELECT id,user_id AS userId,role FROM mess_members WHERE id=? AND mess_id=? AND status=\'active\'',[req.params.memberId,req.params.id]);if(!target)throw new HttpError(404,'Member not found');if(target.userId===req.user.id)throw new HttpError(400,'You cannot remove your own manager account');if(target.role==='manager'){const[[count]]=await pool.execute("SELECT COUNT(*) total FROM mess_members WHERE mess_id=? AND role='manager' AND status='active'",[req.params.id]);if(count.total<=1)throw new HttpError(400,'A mess must have at least one manager');}await transaction(async(conn)=>{await conn.execute("UPDATE mess_members SET status='inactive',left_at=CURDATE() WHERE id=?",[target.id]);await conn.execute('UPDATE cycle_member_status cms JOIN mess_cycles mc ON mc.id=cms.cycle_id SET cms.is_active=0 WHERE cms.mess_member_id=? AND mc.status=\'open\'',[target.id]);await logActivity(conn,+req.params.id,req.user.id,'member.remove','mess_member',target.id);});res.json({ok:true});}));

app.get('/api/dashboard', asyncRoute(async(req,res)=>{const[[mess]]=await pool.execute(`SELECT m.id,m.name,m.address,m.currency,mm.role FROM mess_members mm JOIN messes m ON m.id=mm.mess_id WHERE mm.user_id=? AND mm.status='active' AND m.is_active=1 ORDER BY m.id LIMIT 1`,[req.user.id]);if(!mess)throw new HttpError(404,'Create or join a mess to continue');const[[cycle]]=await pool.execute(`SELECT id,mess_id AS messId,cycle_year AS year,cycle_month AS month,status FROM mess_cycles WHERE mess_id=? ORDER BY status='open' DESC,cycle_year DESC,cycle_month DESC LIMIT 1`,[mess.id]);if(!cycle)throw new HttpError(404,'Open a monthly cycle to continue');const summary=await liveSummary(pool,cycle.id);const[members]=await pool.execute(`SELECT mm.id,u.name,u.email,mm.role,cms.is_active AS active FROM mess_members mm JOIN users u ON u.id=mm.user_id LEFT JOIN cycle_member_status cms ON cms.mess_member_id=mm.id AND cms.cycle_id=? WHERE mm.mess_id=? AND mm.status='active' ORDER BY u.name`,[cycle.id,mess.id]);members.forEach((m,i)=>{m.avatar=m.name.split(/\s+/).map(n=>n[0]).join('').slice(0,2);m.color=avatarColors[i%avatarColors.length];});const[meals]=await pool.execute(`SELECT id,mess_member_id AS memberId,DATE_FORMAT(meal_date,'%Y-%m-%d') date,breakfast,lunch,dinner,guest_meals AS guest FROM meals WHERE cycle_id=? ORDER BY meal_date DESC`,[cycle.id]);const[bazar]=await pool.execute(`SELECT be.id,be.mess_member_id AS memberId,DATE_FORMAT(be.bazar_date,'%Y-%m-%d') date,be.note,be.total_amount AS total,JSON_ARRAYAGG(JSON_OBJECT('product',bi.product_name,'quantity',bi.quantity,'unit',bi.unit,'unitPrice',bi.unit_price)) items FROM bazar_entries be LEFT JOIN bazar_items bi ON bi.bazar_entry_id=be.id WHERE be.cycle_id=? GROUP BY be.id ORDER BY be.bazar_date DESC`,[cycle.id]);const[deposits]=await pool.execute(`SELECT id,mess_member_id AS memberId,amount,DATE_FORMAT(deposit_date,'%Y-%m-%d') date,payment_method AS method FROM deposits WHERE cycle_id=? ORDER BY deposit_date DESC`,[cycle.id]);const[costs]=await pool.execute(`SELECT id,category,title,amount,DATE_FORMAT(cost_date,'%Y-%m-%d') date,split_type AS splitType FROM other_costs WHERE cycle_id=? ORDER BY cost_date DESC`,[cycle.id]);res.json({mess,cycle,summary,members,meals,bazar,deposits,costs});}));

app.use((req,res,next)=>next(new HttpError(404,'Endpoint not found')));
app.use((error,req,res,next)=>{console.error(error);if(error.code==='ER_DUP_ENTRY')return res.status(409).json({message:'This record already exists'});if(error.code==='ER_NO_REFERENCED_ROW_2')return res.status(400).json({message:'A referenced record does not exist'});res.status(error.status||500).json({message:error.status?error.message:'Unexpected server error'});});

const server=app.listen(port,()=>console.log(`Mealora MySQL API running at http://localhost:${port}`));
async function shutdown(){server.close();await pool.end();process.exit(0);}process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);
