<script setup>
import { ref, computed, onMounted } from 'vue';
import { LayoutDashboard, Utensils, ShoppingBasket, WalletCards, ReceiptText, Users, BarChart3, Settings, Bell, Search, ChevronDown, ArrowUpRight, ArrowDownRight, Plus, CalendarDays, MoreHorizontal, X, LogOut, CheckCircle2, LoaderCircle, Menu, Sparkles, CircleDollarSign, Trash2, ShieldCheck, LockKeyhole } from 'lucide-vue-next';
import AdminActions from './components/AdminActions.vue';

const API = import.meta.env.VITE_API_URL || '';
const token = ref(localStorage.getItem('mealora_token') || '');
const user = ref(JSON.parse(localStorage.getItem('mealora_user') || 'null'));
const passwordForm = ref({ currentPassword:'D123', newPassword:'', confirmPassword:'' });
const settingsMesses = ref([]);
const cycles = ref([]), selectedCycleId = ref(null);
const messForm = ref({name:'',address:'',currency:'BDT'});
const cycleForm = ref({messId:null,year:new Date().getFullYear(),month:new Date().getMonth()+1});
const data = ref(null), loading = ref(false), error = ref(''), active = ref('Overview'), modal = ref(''), toast = ref(''), mobileNav = ref(false);
const editingId = ref(null);
const form = ref({});
const nav = [
  { label:'Overview', icon:LayoutDashboard }, { label:'Meals', icon:Utensils }, { label:'Bazar', icon:ShoppingBasket },
  { label:'Deposits', icon:WalletCards }, { label:'Other costs', icon:ReceiptText }, { label:'Members', icon:Users }, { label:'Reports', icon:BarChart3 }
];
const currency = computed(() => data.value?.mess.currency === 'BDT' ? '৳' : data.value?.mess.currency || '৳');
const isManager = computed(() => data.value?.mess.role === 'manager');
const isSuperAdmin = computed(() => user.value?.systemRole === 'super_admin');
const cycleLocked = computed(() => data.value?.cycle.status === 'closed');
const visibleMembers = computed(() => (data.value?.members || []).filter((m) => m.membershipStatus !== 'inactive'));
const modalTitle = computed(() => `${editingId.value ? 'Edit' : ({meal:'Log',bazar:'Add',deposit:'Record',cost:'Add',member:'Invite'}[modal.value])} ${{meal:'daily meals',bazar:'bazar entry',deposit:'deposit',cost:'shared cost',member:'member'}[modal.value] || ''}`);
const bazarGrandTotal = computed(() => (form.value.items || []).reduce((sum,item) => sum + (Number(item.quantity) || 0) * (Number(item.unitPrice) || 0), 0));
const cycleName = computed(() => data.value ? new Date(data.value.cycle.year, data.value.cycle.month-1).toLocaleDateString('en',{month:'long',year:'numeric'}) : '');
const fmt = (v) => `${currency.value}${Number(v || 0).toLocaleString('en-US',{maximumFractionDigits:2})}`;
const dateFmt = (d) => new Date(`${d}T00:00:00`).toLocaleDateString('en',{day:'numeric',month:'short'});
const member = (id) => data.value?.members.find(x => x.id === id) || {};

async function request(path, options={}) { const res = await fetch(`${API}${path}`, { ...options, headers:{ 'Content-Type':'application/json', Authorization:`Bearer ${token.value}`, ...options.headers } }); const json = await res.json().catch(()=>({})); if(res.status===401&&path!=='/api/auth/login'){logout();throw new Error(json.message||'Your session has expired')}if (!res.ok) throw new Error(json.message || 'Something went wrong'); return json; }
async function login() { loading.value=true; error.value=''; try { const result=await request('/api/auth/login',{method:'POST',body:JSON.stringify(form.value)}); token.value=result.token; user.value=result.user; localStorage.setItem('mealora_token',result.token); localStorage.setItem('mealora_user',JSON.stringify(result.user)); if(!result.user.mustChangePassword) await load(); } catch(e){ error.value=e.message } finally { loading.value=false } }
async function changePassword(){error.value='';if(passwordForm.value.newPassword!==passwordForm.value.confirmPassword){error.value='New passwords do not match';return}loading.value=true;try{const result=await request('/api/auth/change-password',{method:'POST',body:JSON.stringify(passwordForm.value)});token.value=result.token;user.value=result.user;localStorage.setItem('mealora_token',result.token);localStorage.setItem('mealora_user',JSON.stringify(result.user));passwordForm.value={currentPassword:'',newPassword:'',confirmPassword:''};await load();flash('Password changed successfully')}catch(e){error.value=e.message}finally{loading.value=false}}
async function load() { if(!token.value) return; loading.value=true; try { const [dashboard,profile]=await Promise.all([request('/api/dashboard'),request('/api/auth/me')]);data.value=dashboard;user.value=profile;selectedCycleId.value=dashboard.cycle.id;cycles.value=await request(`/api/messes/${dashboard.mess.id}/cycles`);localStorage.setItem('mealora_user',JSON.stringify(profile)); } catch(e){ if(e.message.includes('sign in')) logout(); else error.value=e.message } finally { loading.value=false } }
async function switchCycle(){if(!selectedCycleId.value||selectedCycleId.value===data.value?.cycle.id)return;loading.value=true;error.value='';try{data.value=await request(`/api/cycles/${selectedCycleId.value}/dashboard`);flash(`Showing ${cycleName.value}`)}catch(e){error.value=e.message;selectedCycleId.value=data.value?.cycle.id}finally{loading.value=false}}
function cycleOptionLabel(cycle){const name=new Date(cycle.year,cycle.month-1).toLocaleDateString('en',{month:'long',year:'numeric'});return `${name} · ${cycle.status}`}
function logout(){ token.value='';user.value=null;data.value=null;localStorage.removeItem('mealora_token');localStorage.removeItem('mealora_user'); }
function open(type){ editingId.value=null; modal.value=type; error.value=''; const now=new Date().toISOString().slice(0,10), defaultMember=visibleMembers.value[0] || data.value.members[0]; form.value={ date:now, memberId:defaultMember?.id, breakfast:1,lunch:1,dinner:1,guest:0,method:'cash',category:'utility',splitType:'equal',role:'member',items:[{product:'',quantity:1,unit:'kg',unitPrice:0}] }; }
function openEdit(type,row){editingId.value=row.id;modal.value=type;error.value='';form.value=JSON.parse(JSON.stringify(row));if(type==='bazar'&&!Array.isArray(form.value.items))form.value.items=[];}
function flash(message){toast.value=message;setTimeout(()=>toast.value='',2800)}
async function submit(){ loading.value=true; error.value=''; try { let path='', payload={...form.value}; if(modal.value==='meal') path=`/api/cycles/${data.value.cycle.id}/meals`; if(modal.value==='deposit') path=`/api/cycles/${data.value.cycle.id}/deposits`; if(modal.value==='cost') path=`/api/cycles/${data.value.cycle.id}/costs`; if(modal.value==='bazar') path=`/api/cycles/${data.value.cycle.id}/bazar`; if(modal.value==='member') path=`/api/messes/${data.value.mess.id}/members`; const kind=modal.value,wasEditing=Boolean(editingId.value);if(wasEditing)path+=`/${editingId.value}`;await request(path,{method:wasEditing?'PUT':'POST',body:JSON.stringify(payload)});modal.value='';editingId.value=null;await load();flash(kind==='member'?'Member added · temporary password D123':wasEditing?'Updated successfully':'Saved successfully'); } catch(e){error.value=e.message} finally{loading.value=false} }
async function removeEntry(type,row){if(!confirm(`Delete this ${type} record? This cannot be undone.`))return;const paths={meal:'meals',bazar:'bazar',deposit:'deposits',cost:'costs'};loading.value=true;try{await request(`/api/cycles/${data.value.cycle.id}/${paths[type]}/${row.id}`,{method:'DELETE'});await load();flash('Deleted successfully')}catch(e){error.value=e.message;flash(e.message)}finally{loading.value=false}}
async function toggleMember(item){await request(`/api/cycles/${data.value.cycle.id}/members/${item.id}`,{method:'PATCH',body:JSON.stringify({active:!item.active})});await load();}
async function changeRole(item,event){const role=event.target.value;try{await request(`/api/messes/${data.value.mess.id}/members/${item.id}`,{method:'PUT',body:JSON.stringify({role,status:'active'})});await load();flash(`${item.name} is now a ${role}`)}catch(e){error.value=e.message;await load()}}
async function removeMember(item){if(!confirm(`Remove ${item.name} from this mess? Historical records will be kept.`))return;try{await request(`/api/messes/${data.value.mess.id}/members/${item.id}`,{method:'DELETE'});await load();flash('Member removed')}catch(e){error.value=e.message;flash(e.message)}}
async function closeCycle(){if(!confirm('Close this month? Entries will be finalized.'))return;loading.value=true;try{await request(`/api/cycles/${data.value.cycle.id}/close`,{method:'PUT'});await load();flash('Monthly cycle closed')}catch(e){error.value=e.message}finally{loading.value=false}}
async function loadSettings(){if(!isSuperAdmin.value)return;settingsMesses.value=await request('/api/messes');if(!cycleForm.value.messId&&settingsMesses.value.length)cycleForm.value.messId=settingsMesses.value[0].id;}
async function createMess(){loading.value=true;error.value='';try{await request('/api/messes',{method:'POST',body:JSON.stringify(messForm.value)});messForm.value={name:'',address:'',currency:'BDT'};await loadSettings();flash('New mess created')}catch(e){error.value=e.message}finally{loading.value=false}}
async function createCycle(){loading.value=true;error.value='';try{await request(`/api/messes/${cycleForm.value.messId}/cycles`,{method:'POST',body:JSON.stringify({year:Number(cycleForm.value.year),month:Number(cycleForm.value.month)})});await loadSettings();flash('New monthly cycle opened')}catch(e){error.value=e.message}finally{loading.value=false}}
async function go(label){active.value=label;mobileNav.value=false;if(label==='Settings')await loadSettings();}
onMounted(()=>{form.value={email:'',password:''};if(token.value&&!user.value?.mustChangePassword)load()});
</script>

<template>
  <div v-if="!token" class="login-shell">
    <div class="login-art">
      <div class="brand light"><span class="brand-mark"><Utensils :size="20"/></span><span>mealora</span></div>
      <div class="art-copy"><span class="eyebrow dark"><Sparkles :size="14"/> Shared living, simplified</span><h1>More meals.<br/>Less math.</h1><p>One calm place for groceries, meals, deposits, and the numbers that bring everyone together.</p></div>
      <div class="float-card"><div><span>July meal rate</span><strong>৳104.80</strong></div><div class="mini-chart"><i v-for="h in [35,55,42,72,60,88,68]" :style="{height:h+'%'}"></i></div></div>
      <div class="grain"></div>
    </div>
    <main class="login-form"><div class="mobile-brand brand"><span class="brand-mark"><Utensils :size="20"/></span><span>mealora</span></div><div class="login-inner"><span class="eyebrow">Welcome back</span><h2>Sign in to your mess</h2><p>Keep your shared home running smoothly.</p><form @submit.prevent="login"><label>Email address<input v-model="form.email" type="email" required /></label><label>Password<div class="password"><input v-model="form.password" type="password" required/><button type="button">Forgot?</button></div></label><p v-if="error" class="form-error">{{error}}</p><button class="primary full" :disabled="loading"><LoaderCircle v-if="loading" class="spin" :size="18"/>Sign in <ArrowUpRight v-if="!loading" :size="18"/></button></form><div class="demo-note"><CheckCircle2 :size="17"/><span>Use the account registered in your mess database.</span></div></div><small>© 2026 Mealora · Crafted for shared homes</small></main>
  </div>

  <div v-else-if="user?.mustChangePassword" class="password-change-shell">
    <div class="password-change-card">
      <div class="brand"><span class="brand-mark"><Utensils :size="20"/></span><span>mealora</span></div>
      <span class="security-icon"><Settings :size="26"/></span>
      <span class="eyebrow">First login security</span>
      <h1>Create your password</h1>
      <p>You signed in with a temporary password. Choose a private password before continuing to your mess.</p>
      <form @submit.prevent="changePassword">
        <label>Temporary password<input v-model="passwordForm.currentPassword" type="password" required/></label>
        <label>New password<input v-model="passwordForm.newPassword" type="password" minlength="8" placeholder="At least 8 characters" required/></label>
        <label>Confirm new password<input v-model="passwordForm.confirmPassword" type="password" minlength="8" required/></label>
        <p v-if="error" class="form-error">{{error}}</p>
        <button class="primary full" :disabled="loading"><LoaderCircle v-if="loading" class="spin" :size="18"/>Save password and continue</button>
      </form>
      <button class="signout-link" @click="logout"><LogOut :size="15"/>Sign in with another account</button>
    </div>
  </div>

  <div v-else class="app-shell">
    <aside :class="['sidebar',{open:mobileNav}]">
      <div class="brand"><span class="brand-mark"><Utensils :size="20"/></span><span>mealora</span><button class="close-nav" @click="mobileNav=false"><X/></button></div>
      <div class="mess-picker"><span class="avatar violet">GV</span><div><strong>{{data?.mess.name || 'Loading'}}</strong><small>Manager workspace</small></div><ChevronDown :size="16"/></div>
      <nav><span class="nav-title">Workspace</span><button v-for="item in nav" :class="{active:active===item.label}" @click="go(item.label)"><component :is="item.icon" :size="19"/><span>{{item.label}}</span><i v-if="item.label==='Members'">{{visibleMembers.length}}</i></button></nav>
      <div class="side-bottom"><button v-if="isSuperAdmin" :class="{active:active==='Settings'}" @click="go('Settings')"><Settings :size="19"/>System settings</button><button @click="logout"><LogOut :size="19"/>Sign out</button><div class="help-card"><span><Sparkles :size="16"/></span><strong>Keep it balanced</strong><p>Close the cycle once every entry has been checked.</p></div></div>
    </aside>
    <div v-if="mobileNav" class="overlay nav-overlay" @click="mobileNav=false"></div>

    <main class="main">
      <header><button class="menu-btn" @click="mobileNav=true"><Menu/></button><div class="search"><Search :size="18"/><input placeholder="Search anything..."/><kbd>⌘ K</kbd></div><div class="header-actions"><button class="icon-btn"><Bell :size="20"/><i></i></button><span class="divider"></span><div class="profile"><span class="avatar coral">{{user?.avatar}}</span><div><strong>{{user?.name}}</strong><small>{{isSuperAdmin?'Super admin':'Mess member'}}</small></div><ChevronDown :size="15"/></div></div></header>

      <section v-if="data" class="content">
        <div class="page-heading"><div><p class="eyebrow">{{ active==='Overview' ? 'Your monthly pulse' : 'Workspace' }}</p><h1>{{active==='Overview' ? `Good ${new Date().getHours()<12?'morning':new Date().getHours()<17?'afternoon': 'evening'}, ${user.name.split(' ')[0]}` : active}}</h1><p>{{active==='Overview' ? `Here’s how ${data.mess.name} is doing this month.` : `Manage ${active.toLowerCase()} for ${cycleName}.`}}</p></div><div class="heading-actions"><label class="cycle-chip" title="Select monthly cycle"><CalendarDays :size="17"/><select v-model.number="selectedCycleId" @change="switchCycle"><option v-for="cycle in cycles" :value="cycle.id">{{cycleOptionLabel(cycle)}}</option></select><ChevronDown :size="15"/></label><button v-if="active==='Overview' && !cycleLocked" class="primary" @click="open('meal')"><Plus :size="18"/>Add entry</button><button v-if="active==='Meals' && !cycleLocked" class="primary" @click="open('meal')"><Plus :size="18"/>Log meals</button><button v-if="active==='Bazar' && isManager && !cycleLocked" class="primary" @click="open('bazar')"><Plus :size="18"/>Add bazar</button><button v-if="active==='Deposits' && isManager && !cycleLocked" class="primary" @click="open('deposit')"><Plus :size="18"/>Add deposit</button><button v-if="active==='Other costs' && isManager && !cycleLocked" class="primary" @click="open('cost')"><Plus :size="18"/>Add cost</button><button v-if="active==='Members' && isManager" class="primary" @click="open('member')"><Plus :size="18"/>Add member</button></div></div>
        <div v-if="!['Overview','Reports','Settings'].includes(active)" :class="['admin-banner',{locked:cycleLocked,readonly:!isManager}]"><span class="admin-banner-icon"><LockKeyhole v-if="cycleLocked"/><ShieldCheck v-else/></span><div><strong>{{cycleLocked?'Cycle locked':isManager?'Admin controls enabled':'Read-only access'}}</strong><small>{{cycleLocked?'This month is closed. Records are preserved and cannot be changed.':isManager?'You can add, edit, and delete records from this page.':'Only mess managers can update or delete these records.'}}</small></div><span v-if="isManager&&!cycleLocked" class="admin-badge">Manager</span></div>

        <template v-if="active==='Overview'">
          <div class="metric-grid">
            <article class="metric purple"><div class="metric-top"><span class="metric-icon"><Utensils/></span><span class="trend up"><ArrowUpRight/>12.4%</span></div><span>Total meals</span><strong>{{data.summary.totals.meals}}</strong><small>meal units logged</small><div class="metric-orb"></div></article>
            <article class="metric"><div class="metric-top"><span class="metric-icon peach"><ShoppingBasket/></span><span class="trend up"><ArrowUpRight/>6.2%</span></div><span>Bazar spend</span><strong>{{fmt(data.summary.totals.bazar)}}</strong><small>across {{data.bazar.length}} shopping trips</small></article>
            <article class="metric"><div class="metric-top"><span class="metric-icon mint"><CircleDollarSign/></span><span class="trend down"><ArrowDownRight/>2.8%</span></div><span>Current meal rate</span><strong>{{fmt(data.summary.cycle.mealRate)}}</strong><small>per meal unit</small></article>
            <article class="metric"><div class="metric-top"><span class="metric-icon blue"><WalletCards/></span><span class="status-dot">{{data.summary.totals.deposits ? 'On track' : 'Pending'}}</span></div><span>Total deposits</span><strong>{{fmt(data.summary.totals.deposits)}}</strong><small>from {{new Set(data.deposits.map(x=>x.memberId)).size}} of {{visibleMembers.length}} members</small></article>
          </div>
          <div class="dashboard-grid">
            <article class="card spending-card"><div class="card-head"><div><h3>Monthly spending</h3><p>Bazar and shared costs this cycle</p></div><button class="ghost">This month<ChevronDown :size="15"/></button></div><div class="spending-total"><strong>{{fmt(data.summary.totals.bazar+data.summary.totals.otherCost)}}</strong><span class="trend up"><ArrowUpRight/>8.2% vs last month</span></div><div class="bars"><div v-for="(h,i) in [42,56,38,64,47,77,61,85,68,91,73,82]" class="bar-slot"><i :style="{height:h+'%'}" :class="{current:i===11}"></i></div></div><div class="bar-labels"><span>Week 1</span><span>Week 2</span><span>Week 3</span><span>Week 4</span></div></article>
            <article class="card quick-card"><div class="card-head"><div><h3>Quick entry</h3><p>What would you like to record?</p></div></div><div class="quick-grid"><button @click="open('meal')"><span class="metric-icon purple-soft"><Utensils/></span><div><strong>Daily meals</strong><small>Log member meals</small></div><Plus/></button><button @click="open('bazar')"><span class="metric-icon peach"><ShoppingBasket/></span><div><strong>Bazar</strong><small>Add shopping items</small></div><Plus/></button><button @click="open('deposit')"><span class="metric-icon mint"><WalletCards/></span><div><strong>Deposit</strong><small>Record a payment</small></div><Plus/></button><button @click="open('cost')"><span class="metric-icon blue"><ReceiptText/></span><div><strong>Other cost</strong><small>Utilities, rent & more</small></div><Plus/></button></div></article>
          </div>
          <div class="lower-grid">
            <article class="card"><div class="card-head"><div><h3>Member balance</h3><p>Live estimate for {{cycleName}}</p></div><button class="link-btn" @click="go('Reports')">View report <ArrowUpRight :size="16"/></button></div><div class="member-list"><div v-for="m in data.summary.members.slice(0,5)" class="member-row"><span class="avatar" :style="{background:m.color}">{{m.avatar}}</span><div class="member-name"><strong>{{m.name}}</strong><small>{{m.meals}} meals · {{fmt(m.totalCost)}} cost</small></div><span :class="['balance',m.status]">{{m.balance>=0?'+':'−'}}{{fmt(Math.abs(m.balance))}}<small>{{m.status}}</small></span></div></div></article>
            <article class="card"><div class="card-head"><div><h3>Recent bazar</h3><p>Latest grocery activity</p></div><button class="icon-plain"><MoreHorizontal/></button></div><div class="bazar-list"><div v-for="b in data.bazar.slice(0,4)" class="bazar-row"><div class="date-block"><strong>{{new Date(b.date+'T00:00:00').getDate()}}</strong><span>{{new Date(b.date+'T00:00:00').toLocaleDateString('en',{month:'short'})}}</span></div><div><strong>{{b.note}}</strong><small>{{member(b.memberId).name}} · {{b.items.length}} items</small></div><strong>{{fmt(b.total)}}</strong></div></div></article>
          </div>
        </template>

        <article v-else-if="active==='Meals'" class="card table-card management-card"><div class="card-head"><div><h3>Daily meal register</h3><p>Breakfast, lunch, dinner and guest meals</p></div></div><div class="responsive-table"><table><thead><tr><th>Date</th><th>Member</th><th>Breakfast</th><th>Lunch</th><th>Dinner</th><th>Guest</th><th>Total</th><th v-if="isManager" class="actions-column">Admin actions</th></tr></thead><tbody><tr v-for="row in data.meals"><td>{{dateFmt(row.date)}}</td><td><div class="person"><span class="avatar" :style="{background:member(row.memberId).color}">{{member(row.memberId).avatar}}</span>{{member(row.memberId).name}}</div></td><td>{{row.breakfast}}</td><td>{{row.lunch}}</td><td>{{row.dinner}}</td><td>{{row.guest}}</td><td><strong>{{row.breakfast+row.lunch+row.dinner+row.guest}}</strong></td><td v-if="isManager" class="actions-column"><AdminActions :disabled="cycleLocked" @edit="openEdit('meal',row)" @remove="removeEntry('meal',row)"/></td></tr></tbody></table></div></article>
        <article v-else-if="active==='Bazar'" class="card table-card management-card"><div class="responsive-table"><table><thead><tr><th>Date</th><th>Shopper</th><th>Description</th><th>Items</th><th>Amount</th><th v-if="isManager" class="actions-column">Admin actions</th></tr></thead><tbody><tr v-for="row in data.bazar"><td>{{dateFmt(row.date)}}</td><td>{{member(row.memberId).name}}</td><td><strong>{{row.note}}</strong></td><td>{{row.items.map(x=>x.product).join(', ')}}</td><td><strong>{{fmt(row.total)}}</strong></td><td v-if="isManager" class="actions-column"><AdminActions :disabled="cycleLocked" @edit="openEdit('bazar',row)" @remove="removeEntry('bazar',row)"/></td></tr></tbody></table></div></article>
        <article v-else-if="active==='Deposits'" class="card table-card management-card"><div class="responsive-table"><table><thead><tr><th>Date</th><th>Member</th><th>Method</th><th>Amount</th><th>Status</th><th v-if="isManager" class="actions-column">Admin actions</th></tr></thead><tbody><tr v-for="row in data.deposits"><td>{{dateFmt(row.date)}}</td><td>{{member(row.memberId).name}}</td><td><span class="method">{{row.method}}</span></td><td><strong>{{fmt(row.amount)}}</strong></td><td><span class="paid">Received</span></td><td v-if="isManager" class="actions-column"><AdminActions :disabled="cycleLocked" @edit="openEdit('deposit',row)" @remove="removeEntry('deposit',row)"/></td></tr></tbody></table></div></article>
        <article v-else-if="active==='Other costs'" class="card table-card management-card"><div class="responsive-table"><table><thead><tr><th>Date</th><th>Cost</th><th>Category</th><th>Split</th><th>Amount</th><th v-if="isManager" class="actions-column">Admin actions</th></tr></thead><tbody><tr v-for="row in data.costs"><td>{{dateFmt(row.date)}}</td><td><strong>{{row.title}}</strong></td><td>{{row.category}}</td><td>{{row.splitType==='equal'?'Equal split':'By meals'}}</td><td><strong>{{fmt(row.amount)}}</strong></td><td v-if="isManager" class="actions-column"><AdminActions :disabled="cycleLocked" @edit="openEdit('cost',row)" @remove="removeEntry('cost',row)"/></td></tr></tbody></table></div></article>
        <article v-else-if="active==='Members'" class="card"><div class="card-head"><div><h3>Members & permissions</h3><p>Change roles and choose who is included in this month's shared costs</p></div></div><div class="member-cards"><div v-for="m in visibleMembers" class="member-card"><span class="avatar large" :style="{background:m.color}">{{m.avatar}}</span><div><strong>{{m.name}}</strong><small>{{m.email}}</small><select v-if="isManager" class="role-select" :value="m.role" @change="changeRole(m,$event)"><option value="member">Member</option><option value="manager">Manager</option></select><span v-else class="role-label">{{m.role}}</span></div><label class="participation"><span>Active this month</span><button type="button" :disabled="!isManager||cycleLocked" :class="['toggle',{on:m.active}]" @click="toggleMember(m)"><i></i></button></label><button v-if="isManager" class="member-remove labeled" @click="removeMember(m)" title="Remove member"><Trash2/><span>Remove</span></button></div></div></article>
        <div v-else-if="active==='Settings' && isSuperAdmin" class="settings-layout"><div class="superadmin-banner"><span><ShieldCheck/></span><div><p class="eyebrow">System access</p><h2>Super admin controls</h2><small>Only global super administrators can create messes and monthly cycles.</small></div><strong>SUPER ADMIN</strong></div><article class="card settings-card"><div class="settings-icon"><Users/></div><div class="card-head"><div><h3>Create a new mess</h3><p>The creator is automatically assigned as its first manager.</p></div></div><form @submit.prevent="createMess"><label>Mess name<input v-model="messForm.name" placeholder="e.g. Green Villa" required/></label><label>Address<input v-model="messForm.address" placeholder="Area, city"/></label><label>Currency<select v-model="messForm.currency"><option value="BDT">BDT — Bangladeshi Taka</option><option value="USD">USD — US Dollar</option><option value="INR">INR — Indian Rupee</option></select></label><button class="primary" :disabled="loading"><Plus/>Create mess</button></form></article><article class="card settings-card"><div class="settings-icon cycle"><CalendarDays/></div><div class="card-head"><div><h3>Open a monthly cycle</h3><p>Select a mess and the calendar month to activate.</p></div></div><form @submit.prevent="createCycle"><label>Mess<select v-model.number="cycleForm.messId" required><option v-for="mess in settingsMesses" :value="mess.id">{{mess.name}}</option></select></label><div class="field-grid"><label>Year<input v-model.number="cycleForm.year" type="number" min="2020" max="2100" required/></label><label>Month<select v-model.number="cycleForm.month"><option v-for="n in 12" :value="n">{{new Date(2026,n-1).toLocaleDateString('en',{month:'long'})}}</option></select></label></div><button class="primary" :disabled="loading||!cycleForm.messId"><Plus/>Open cycle</button></form></article><p v-if="error" class="form-error settings-error">{{error}}</p></div>
        <div v-else-if="active==='Reports'" class="report-layout"><article class="card report-hero"><span class="eyebrow">Live statement</span><h2>{{cycleName}} settlement</h2><p>Calculated from meals, groceries, shared expenses and deposits.</p><div><span><small>Meal rate</small><strong>{{fmt(data.summary.cycle.mealRate)}}</strong></span><span><small>Total outflow</small><strong>{{fmt(data.summary.totals.bazar+data.summary.totals.otherCost)}}</strong></span><span><small>Cycle status</small><strong class="capitalize">{{data.cycle.status}}</strong></span></div><button class="primary light-btn" :disabled="data.cycle.status==='closed'" @click="closeCycle">{{data.cycle.status==='closed'?'Cycle closed':'Close monthly cycle'}}</button></article><article class="card"><div class="card-head"><div><h3>Settlement breakdown</h3><p>Positive balances are refunds; negative balances are due.</p></div></div><div class="member-list"><div v-for="m in data.summary.members" class="member-row"><span class="avatar" :style="{background:m.color}">{{m.avatar}}</span><div class="member-name"><strong>{{m.name}}</strong><small>{{fmt(m.deposit)}} deposited · {{fmt(m.totalCost)}} cost</small></div><span :class="['balance',m.status]">{{m.balance>=0?'+':'−'}}{{fmt(Math.abs(m.balance))}}<small>{{m.status}}</small></span></div></div></article></div>
      </section>
      <div v-else class="page-loader"><LoaderCircle class="spin"/><span>Preparing your dashboard…</span></div>
    </main>

    <div v-if="modal" class="overlay modal-overlay" @mousedown.self="modal=''">
      <form class="modal" @submit.prevent="submit"><div class="modal-head"><div><span class="eyebrow">{{editingId ? 'Update record' : 'New record'}}</span><h2>{{modalTitle}}</h2></div><button type="button" @click="modal=''"> <X/> </button></div>
        <div v-if="modal!=='member'" class="field-grid"><label v-if="['meal','bazar','deposit'].includes(modal)">Member<select v-model.number="form.memberId"><option v-for="m in visibleMembers" :value="m.id">{{m.name}}</option></select></label><label>Date<input v-model="form.date" type="date" required/></label></div>
        <div v-if="modal==='meal'" class="meal-inputs"><label>Breakfast<input v-model.number="form.breakfast" type="number" step="0.5" min="0"/></label><label>Lunch<input v-model.number="form.lunch" type="number" step="0.5" min="0"/></label><label>Dinner<input v-model.number="form.dinner" type="number" step="0.5" min="0"/></label><label>Guest<input v-model.number="form.guest" type="number" step="0.5" min="0"/></label></div>
        <template v-if="modal==='bazar'"><label>Note<input v-model="form.note" placeholder="e.g. Weekly groceries"/></label><div class="items"><div class="item-head"><span>Product</span><span>Qty</span><span>Unit</span><span>Unit price</span><span>Subtotal</span><span></span></div><div v-for="(item,i) in form.items" class="item-row"><input v-model="item.product" placeholder="Product" required/><input v-model.number="item.quantity" type="number" min="0.001" step="any" inputmode="decimal" placeholder="Qty" required/><select v-model="item.unit"><option>kg</option><option>liter</option><option>pcs</option><option>lot</option></select><input v-model.number="item.unitPrice" type="number" min="0" step="any" inputmode="decimal" placeholder="Unit price" required/><strong class="line-subtotal">{{fmt((Number(item.quantity)||0)*(Number(item.unitPrice)||0))}}</strong><button type="button" @click="form.items.splice(i,1)" title="Remove item"><X :size="16"/></button></div><div class="items-footer"><button type="button" class="add-line" @click="form.items.push({product:'',quantity:1,unit:'kg',unitPrice:0})"><Plus :size="16"/>Add another item</button><div><span>Grand total</span><strong>{{fmt(bazarGrandTotal)}}</strong></div></div></div></template>
        <template v-if="modal==='deposit'"><label>Amount<input v-model.number="form.amount" type="number" min="1" placeholder="0.00" required/></label><label>Payment method<select v-model="form.method"><option value="cash">Cash</option><option value="bkash">bKash</option><option value="nagad">Nagad</option><option value="bank">Bank</option><option value="other">Other</option></select></label></template>
        <template v-if="modal==='cost'"><label>Title<input v-model="form.title" placeholder="e.g. Electricity bill" required/></label><div class="field-grid"><label>Category<select v-model="form.category"><option value="utility">Utility</option><option value="rent">Rent</option><option value="servant">House help</option><option value="maintenance">Maintenance</option><option value="other">Other</option></select></label><label>Amount<input v-model.number="form.amount" type="number" min="1" required/></label></div><label>Split rule<select v-model="form.splitType"><option value="equal">Equally among active members</option><option value="meal_based">Based on meal ratio</option></select></label></template>
        <template v-if="modal==='member'"><label>Full name<input v-model="form.name" placeholder="Member name" required/></label><label>Email<input v-model="form.email" type="email" placeholder="member@example.com" required/></label><label>Role<select v-model="form.role"><option value="member">Member</option><option value="manager">Manager</option></select></label></template>
        <p v-if="error" class="form-error">{{error}}</p><div class="modal-actions"><button type="button" class="ghost" @click="modal=''">Cancel</button><button class="primary" :disabled="loading"><LoaderCircle v-if="loading" class="spin" :size="17"/>{{editingId ? 'Update entry' : 'Save entry'}}</button></div>
      </form>
    </div>
    <Transition name="toast"><div v-if="toast" class="toast"><CheckCircle2/>{{toast}}</div></Transition>
  </div>
</template>
